### ISSUE TITLE
字典获取值的错误

### ISSUE THREAD

**Issue by zhangyucumt** [zwczou/weixin-python#14]
https://github.com/zwczou/weixin-python/blob/a25ff4185a5526a361e4315a6d3485a1f9b67e69/weixin/msg.py#L174

https://github.com/zwczou/weixin-python/blob/a25ff4185a5526a361e4315a6d3485a1f9b67e69/weixin/msg.py#L178

这俩处获取字典中的值有误

**Comment by zwczou** [comment]
谢谢指正
