### ISSUE TITLE
Python3 support?

### ISSUE THREAD

**Issue by ghost** [zwczou/weixin-python#2]
安装的时候出现了错误，但是安装上了。

···
Running setup.py install for weixin-python
      File ".../python3.4/site-packages/weixin/pay.py", line 89
        except urllib2.HTTPError, e:
                                ^
    SyntaxError: invalid syntax
···

使用的时候出现了下面的错误：
···
    from weixin.login import WeixinLogin
  File ".../python3.4/site-packages/weixin/__init__.py", line 6, in <module>
    from msg import WeixinMsg
ImportError: No module named 'msg'
···
有支持Python 3的盼头么？

**Comment by ghost** [comment]
使用2to3工具转换之后基本可以用了，不过仍然有以下错误

```
  File ".../weixin/login.py", line 36, in get
    data = Map(json.loads(resp.read()))
  File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

不过这样的问题可以通过decode解决，贴到这里希望对后来者有用吧。

**Comment by zwczou** [comment]
准备下个版本支持python3，当前有个dev分支，正在做这个事情

**Comment by zwczou** [comment]
新版本已经支持python3
