### ISSUE TITLE
你好，创建微信公众号菜单怎么使用？

### ISSUE THREAD

**Issue by wangy09** [zwczou/weixin-python#23]
你好，创建微信公众号菜单怎么使用？
xxxxxx
weixin = Weixin()
weixin.init_app(app)
初始化完成后应该怎么做

**Comment by zwczou** [comment]
```python
data = [
    {
        "type": "view",
        "name": "测试",
        "url": "http://code.show/",
    },
]
print mp.menu_create(data)
```

可以参考 [这里](https://github.com/zwczou/weixin-python/blob/dev/example/mp.py)

**Comment by wangy09** [comment]
谢谢，刚看了一下你的源码
xxxxxx
weixin = Weixin()
weixin.init_app(app)
创建菜单
data = [
    {
        "type": "view",
        "name": "测试",
        "url": "http://code.show/",
    },
]
weixin.mp.menu_create(data)

**Comment by wangy09** [comment]
你好，有两个问题，请指教，python版本v3.6.2
  

1.菜单为中文名字时候报错40033，英文则没有问题

![image](https://user-images.githubusercontent.com/16033197/40709028-8f248cae-6427-11e8-928a-0086c8dcc188.png)


2.关注公众号后报错 
![image](https://user-images.githubusercontent.com/16033197/40709092-b4c5955c-6427-11e8-84b7-4f8c33af07ff.png)

代码如下所示：  
`from weixin import Weixin, WeixinError
app.config['WEIXIN_APP_ID'] = appglobal.config["WX_OPTION"]["APPID"]
app.config['WEIXIN_APP_SECRET'] = appglobal.config["WX_OPTION"]["APPSECRET"]
app.config['WEIXIN_SENDER'] = appglobal.config["WX_OPTION"]["WEIXIN_SENDER"]
app.config['WEIXIN_EXPIRES_IN'] = appglobal.config["WX_OPTION"]["WEIXIN_EXPIRES_IN"]
app.config['WEIXIN_TOKEN']=appglobal.config["WX_OPTION"]["WEIXIN_TOKEN"]
'''初始化微信'''
weixin = Weixin()
weixin.init_app(app)
app.add_url_rule("/", view_func=weixin.view_func)

'''创建菜单'''
data = [
    {
        "type": "view",
        "name": "测试1",
        "url": "http://www.baidu.com"
    },
    {
        "type": "click",
        "name": "测试2",
        "key": "menu_bdtj"
    }
]
weixin.mp.menu_create(data)

@weixin.all
def all(**kwargs):
    """
    监听所有没有更特殊的事件
    """
    return weixin.reply(kwargs['sender'], sender=kwargs['receiver'], content='all')


@weixin.text()
def hello(**kwargs):
    """
    监听所有文本消息
    """
    return "hello too"


@weixin.text("help")
def world(**kwargs):
    """
    监听help消息
    """
    return dict(content="hello world!")


@weixin.subscribe
def subscribe(**kwargs):
    """
    监听订阅消息
    """
    print(kwargs)
    return "欢迎订阅我们的公众号"`
