### ISSUE TITLE
你好，自定义菜单和消息有两个问题，请指教，python版本v3.6.2

### ISSUE THREAD

**Issue by wangy09** [zwczou/weixin-python#24]
你好，有两个问题，请指教，python版本v3.6.2
  

1.菜单为中文名字时候报错40033，英文则没有问题

![image](https://user-images.githubusercontent.com/16033197/40709028-8f248cae-6427-11e8-928a-0086c8dcc188.png)

2.关注公众号后报错 
![image](https://user-images.githubusercontent.com/16033197/40709092-b4c5955c-6427-11e8-84b7-4f8c33af07ff.png)

代码如下所示：  
`from weixin import Weixin, WeixinError
app.config['WEIXIN_APP_ID'] = appglobal.config["WX_OPTION"]["APPID"]
app.config['WEIXIN_APP_SECRET'] = appglobal.config["WX_OPTION"]["APPSECRET"]
app.config['WEIXIN_SENDER'] = appglobal.config["WX_OPTION"]["WEIXIN_SENDER"]
app.config['WEIXIN_EXPIRES_IN'] = appglobal.config["WX_OPTION"]["WEIXIN_EXPIRES_IN"]
app.config['WEIXIN_TOKEN']=appglobal.config["WX_OPTION"]["WEIXIN_TOKEN"]
'''初始化微信'''
weixin = Weixin()
weixin.init_app(app)
app.add_url_rule("/", view_func=weixin.view_func)

'''创建菜单'''
data = [
    {
        "type": "view",
        "name": "测试1",
        "url": "http://www.baidu.com"
    },
    {
        "type": "click",
        "name": "测试2",
        "key": "menu_bdtj"
    }
]
weixin.mp.menu_create(data)

@weixin.all
def all(**kwargs):
    """
    监听所有没有更特殊的事件
    """
    return weixin.reply(kwargs['sender'], sender=kwargs['receiver'], content='all')

@weixin.text()
def hello(**kwargs):
    """
    监听所有文本消息
    """
    return "hello too"

@weixin.text("help")
def world(**kwargs):
    """
    监听help消息
    """
    return dict(content="hello world!")

@weixin.subscribe
def subscribe(**kwargs):
    """
    监听订阅消息
    """
    print(kwargs)
    return "欢迎订阅我们的公众号"`

**Comment by zwczou** [comment]
1. 问题一，应该是编码问题，可以将mp.py里面的102行改成101行试试
```python
data = json.dumps(data, ensure_ascii=False)
```
2. 很明显的语法错误，可以提供更完整的错误信息么
