### ISSUE TITLE
[功能需求]希望支付接口地址可以自定义

### ISSUE THREAD

**Issue by duzhipeng** [zwczou/weixin-python#27]
原因是微信支付提供了沙盒地址：https://api.mch.weixin.qq.com/sandboxnew/pay/getsignkey
具体：https://pay.weixin.qq.com/wiki/doc/api/native.php?chapter=23_1

为了便于开发调试，希望SDK不要写死请求接口的地址，而允许开发者写到配置文件中，这样我们开发的时候可以在测试环境定义为沙盒地址。

**Comment by zwczou** [comment]
谢谢你的建议，预计下个版本提出hosts

**Comment by zwczou** [comment]
最新版本已经提出来了
