### ISSUE TITLE
电脑网站支付

### ISSUE THREAD

**Issue by GuoYangguang** [zwczou/weixin-python#31]
这个包开发得真好，很规范。但是不知道支不支持电脑网站（Pc电脑）支付？谢谢答复！

**Comment by zwczou** [comment]
你指的是扫二维码支付么？是支持的

**Comment by GuoYangguang** [comment]
是二维码支付，电脑网站上支付，而不是手机浏览器或者微信里的网页支付， 问下支持吗？

**Comment by zwczou** [comment]
可以看文档 [统一下单](https://github.com/zwczou/weixin-python/wiki/%E5%BE%AE%E4%BF%A1%E6%94%AF%E4%BB%98#%E7%BB%9F%E4%B8%80%E4%B8%8B%E5%8D%95)

其中`trade_type`更改为 'NATIVE' 其中 `openid`不需要写入，而更改为`product_id`

具体文档可以参考微信扫二维码支付 https://pay.weixin.qq.com/wiki/doc/api/native.php?chapter=9_1

**Comment by GuoYangguang** [comment]
感谢回复，你是专家，后边有问题， 再向你请教。
