### ISSUE TITLE
微信退款报ssl的问题

### ISSUE THREAD

**Issue by xjblszyy** [zwczou/weixin-python#32]
请问大家也遇到这个问题吗
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.mch.weixin.qq.com', port=443): Max retries exceeded with url: /secapi/pay/refund (Caused by SSLError(SSLError(336445449, '[SSL] PEM lib (_ssl.c:3337)'),))

**Comment by zwczou** [comment]
cert跟key放错了位置？

**Comment by xjblszyy** [comment]
谢老哥，我确实写错了~~~~(>_<)~~~~
