### ISSUE TITLE
代码质量 Cookie：未设置HttpOnly标记

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [zwczou/weixin-python#35]
您好，我是奇虎360代码卫士团队的工作人员，在我们的开源项目检测中发现weixin-python存在代码质量 Cookie：未设置HttpOnly标记隐患，详细信息如下： 
![image](https://user-images.githubusercontent.com/39950310/49424282-13f94c80-f7d5-11e8-9a36-b0aa71e915c5.png)
在weixin-python-dev/example/login.py文件 第38行 ，程序生成Cookie时，未设置HTTPOnly标记，存在安全风险。为Cookie设置HTTPOnly标记，浏览器将不允许客户端脚本访问Cookie，可有效缓解XSS漏洞造成的威胁。可以改成 resp.set_cookie("openid", openid, expires=expires，httponly=True)

**Comment by zwczou** [comment]
谢谢建议
