### ISSUE TITLE
encode编码问题

### ISSUE THREAD

**Issue by simple5510** [zwczou/weixin-python#44]
使用django2.1 微信支付异步通知传回的数据，调用to_dict方法时，调用了encode，python3.7会报错，我改成了decode后可以继续执行

**Comment by zwczou** [comment]
谢谢反馈，估计是编码兼容性问题

**Comment by byte-voyager** [comment]
此bug希望更改

> 谢谢反馈，估计是编码兼容性问题

**Comment by zwczou** [comment]
由于兼容python2/3的问题，建议在to_dict之前做encode/decode处理
