### ISSUE TITLE
add_query未去除干净，比如在qrcode_show方法里

### ISSUE THREAD

**Issue by zzyykk123456** [zwczou/weixin-python#48]

**Comment by zwczou** [comment]
?

**Comment by zzyykk123456** [comment]
最新代码里add_query方法，没有定义，该去掉吧发自我的华为手机-------- 原始邮件 --------主题：Re: [zwczou/weixin-python] add_query未去除干净，比如在qrcode_show方法里 (#48)发件人：zwc 收件人：zwczou/weixin-python 抄送：zzyykk123456 ,Author ?

**Comment by zwczou** [comment]
已经修复，谢谢反馈，可以尝试升级最新版本解决
