### ISSUE TITLE
mp.py文件中post方法,参数data有中文时报40033错。json.dumps应该使用注释的才对。

### ISSUE THREAD

**Issue by tzbts** [zwczou/weixin-python#49]

**Comment by zwczou** [comment]
使用注释的代码会引起其他问题，貌似可以通过 str.encode, str.decode来解决这个问题
你可以尝试下

**Comment by tzbts** [comment]
encode能解决这个问题，并且解决了一个bug，提交了代码，您有时间看一下

**Comment by hardenCN** [comment]
直接用post创建菜单
`mp.post("/menu/create", button_menu_dict_string, json_encode=False)`

**Comment by zwczou** [comment]
这个不建议更改，因为你使用unicode跟str的问题.所以
