### ISSUE TITLE
老师好！您的程序包很棒！但我使用时，进不了微信输密码、支付的界面，是怎么回事？

### ISSUE THREAD

**Issue by lyl1836** [zwczou/weixin-python#51]
1、支付代码：
raw = weixin.jsapi(openid="oveOgwW7Q5I-xxxxxxxx", body=u"测试", out_trade_no=out_trade_no, total_fee=1, attach="支付赏金")
成功得到： raw , 但未见到微信付款的界面；
2、查询订单：
weixin.order_query(out_trade_no=out_trade_no)
结果为：
![image](https://user-images.githubusercontent.com/48607893/64304484-8c887600-cfbe-11e9-9c21-25246460e9d5.png)

请问我哪里做错了？请老师指导 一下，非常感谢！

**Comment by zwczou** [comment]
你应该有个h5页面，在微信里面打开，然后h5页面里面拿着你这个raw，用来发起支付

**Comment by zwczou** [comment]
具体文档可以参考 https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=7_7&index=6

```
WeixinJSBridge.invoke(
      'getBrandWCPayRequest', {
         "appId":"wx2421b1c4370ec43b",     //公众号名称，由商户传入     
         "timeStamp":"1395712654",         //时间戳，自1970年以来的秒数     
         "nonceStr":"e61463f8efa94090b1f366cccfbbb444", //随机串     
         "package":"prepay_id=u802345jgfjsdfgsdg888",     
         "signType":"MD5",         //微信签名方式：     
         "paySign":"70EA570631E4BB79628FBCA90534C63FF7FADD89" //微信签名 
      },
      function(res){
      if(res.err_msg == "get_brand_wcpay_request:ok" ){
      // 使用以上方式判断前端返回,微信团队郑重提示：
            //res.err_msg将在用户支付成功后返回ok，但并不保证它绝对可靠。
      } 
   }); 
```

**Comment by lyl1836** [comment]
老师回复这么快捷，远超我的预期！非常感谢老师！我来试一下！
