### ISSUE TITLE
python3中没有basestring

### ISSUE THREAD

**Issue by vaakian** [zwczou/weixin-python#54]
环境：python3.7
微信消息推送出现
`NameError: name 'basestring' is not defined`

我目前解决方案是在msg.py 内添加了一行
```python3 
basestring = (str, bytes)
```

**Comment by vaakian** [comment]
翻了一下，大家居然没有提这个issue，所以怀疑是我自己的操作有问题，或者大家都是用的python2？

**Comment by zwczou** [comment]
你是python3.x ? basestring在base.py里面有兼容代码
