### ISSUE TITLE
AttributeError: invalid attribute "notify_url"

### ISSUE THREAD

**Issue by Near-Tam** [zwczou/weixin-python#61]
File "/home/tzy/venvs/wxpay/lib/python2.7/site-packages/weixin/msg.py", line 216, in __getattr__
    raise AttributeError('invalid attribute "' + key + '"')
AttributeError: invalid attribute "notify_url

请问这个问题怎么解决
python == 2.7.5
用的是flask框架
调用pay_jsapi接口时报错

**Comment by jc-ding** [comment]
同样问题，python3.7

**Comment by ooodjc** [comment]
你应该是初始化错误，参考/docs/pay里的案例，别用首页文档里写的
