### ISSUE TITLE
python3 自动消息回复有中文情况下，微信端收到的是 \uxxx 类型的编码的解决方案

### ISSUE THREAD

**Issue by zsenliao** [zwczou/weixin-python#67]
修改`msg.py`文件中以下部分：
```python
def text_reply(username, sender, content):
    shared = _shared_reply(username, sender, "text")
    template = f"<xml>{shared}<Content><![CDATA[{content}]]></Content></xml>".encode(
        "utf-8"
    )
    return template
```
之后微信端收到的就是正常的中文字符了。因为我的使用环境是python3，python2中没有测试，所以就不提pr啦

**Comment by zwczou** [comment]
这个与你传入进来的content的编码有关系吧。你可以尝试对传入进来的content decode/encode测试下

**Comment by zsenliao** [comment]
> 这个与你传入进来的content的编码有关系吧。你可以尝试对传入进来的content decode/encode测试下

我传入的是 str，content encode("utf8") 之后，微信上看到的一样是编码字符。
