### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by byte-voyager** [zwczou/weixin-python#74]
Python3.6
Flask 1.1.2

* 文档 微信回调应该是POST，Flask文档没写此参数
```
@bp.route('/wx_pay/pay_notify', methods=['POST'])
```
* request.data是bytes类型，在py3转化为string调用的是decode方法

建议：兼容Python3

**Comment by zwczou** [comment]
欢迎提交 pull requests

**Comment by zwczou** [comment]
文档更新了，但是编码的问题，我建议在to_dict之前来处理，不然python2/3 兼容起来麻烦
