### ISSUE TITLE
pay 支付回调字符编码问题

### ISSUE THREAD

**Issue by TigerShuai** [zwczou/weixin-python#75]
```
    def to_dict(self, content):
        raw = {}
        content = content.encode(errors='replace') if isinstance(content, str) else content.decode(errors='replace')
        root = etree.fromstring(content,
                                parser=etree.XMLParser(resolve_entities=False))
        for child in root:
            raw[child.tag] = child.text
        return raw
```
这样兼容python3.5以上的多个python版本，望采纳

**Comment by zwczou** [comment]
感谢，等我测试过后，再提交进来

**Comment by TigerShuai** [comment]
我使用的是python3.7版本，印象当中python3.5之后字符转换源码有修改，惯用方法在python3.5之后会报错，提示decode编码问题。


| |
研发部王帅
|
|
15617699933@163.com
|
签名由网易邮箱大师定制


在2020年11月16日 16:08，zwc<notifications@github.com> 写道：

感谢，等我测试过后，再提交进来

**Comment by TigerShuai** [comment]
老哥，框架我用了下，现在有个问题，我生产环境已经上线了，但是本地迭代时，微信提供的有测试公众号，但是发现access_token，和jsapi_ticket是共用的，mp.py的钥匙都是写在本地磁盘的，这样导致我本地开发迭代时，正式环境的access_token，和jsapi_ticket就会失效了，后续有考虑增加redis存储吗或者有什么更好的方案，感谢🙏

**Comment by zwczou** [comment]
def __init__(self, app_id, app_secret, ac_path=None, jt_path=None, ac_callback=None, jt_callback=None):

可以传入ac_callback, js_callback自己覆盖。

**Comment by TigerShuai** [comment]
嗯，我增加了mp.py的redis相关参数，flask初始化项目时，传递redis相关config 配置项
