### ISSUE TITLE
退款回调数据解密

### ISSUE THREAD

**Issue by byte-voyager** [zwczou/weixin-python#76]
微信文档
解密方式
解密步骤如下：
（1）对加密串A做base64解码，得到加密串B
（2）对商户key做md5，得到32位小写key* ( key设置路径：微信商户平台(pay.weixin.qq.com)-->账户设置-->API安全-->密钥设置 )

（3）用key*对加密串B做AES-256-ECB解密（PKCS7Padding）

这个是在此项目没实现吗？

**Comment by zwczou** [comment]
没有实现

**Comment by zwczou** [comment]
这个可以在你的项目API层里面自己实现这部分逻辑了
